# Generated by Django 3.2.7 on 2021-10-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=256)),
                ('image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
